---
- name: "configure device"
  hosts: all
  roles: 
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: "Configure op script"
      juniper_junos_config:
        config_mode: "private"
        load: "set"
        lines:
          - set firewall policer Police-IPv4-Client-{{ item.value.clientname }} if-exceeding bandwidth-limit {{ item.value.bandwidth }}m
          - set firewall policer Police-IPv4-Client-{{ item.value.clientname }} if-exceeding burst-size-limit {{ item.value.burstlimit }}m
          - set firewall policer Police-IPv4-Client-{{ item.value.clientname }} then discard
    - name: "Print the config changes"
      debug: 
        var: {response.diff_lines}
